config/routes.rb
Va::Application.routes.draw do

  resource :registration, :only => [:new, :create, :edit, :update, :password, :destroy], :as => :users,
      :path_names => {:new => :sign_up}, :member => {:validate => :post}, :collection => {:regions => :get, :cities => :get}
  
  scope 'session' do
    get 'sign_in' => 'user_sessions#new', :as => :new_user_session
    post 'sign_in' => 'user_sessions#create', :as => :user_session
    get 'sign_out' => 'user_sessions#destroy', :as => :destroy_user_session
  end
  
  resources :users
  match "live_validations/:action" => 'live_validations'
  root :to => 'users#me'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  
  belongs_to :user
  
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items
  has_one :order

  def total_price
    # convert to array so it doesn't try to do sum on database directly
    line_items.to_a.sum(&:full_price)
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/city.rb
class City < ActiveRecord::Base
  
  establish_connection :ref_area

  default_scope :order => :name
  belongs_to :country
  belongs_to :region
  
end

app/models/country.rb
class Country < ActiveRecord::Base
  
  establish_connection :ref_area
  
  default_scope :order => :name
  has_many :regions
  has_many :cities
  
  def get_flag
    "flags/small/" + iso2.downcase + ".gif"
  end
  
  def self.get_flag(iso2)
    iso2 = iso2.downcase
    "flags/small/" + iso2 + ".gif"
  end
  
  def self.get_flag_by_name(name)
    "flags/medium/" + name.sub(' ', '_') + ".png"
  end
  
  def self.get_flag_from_iso3(iso3)
    country = Country.find_by_iso3(iso3)
    return get_flag(country.iso2)
  end
  
  def self.get_flag_from_ison(ison)
    country = Country.find_by_ison(ison)
    return get_flag(country.iso2)
  end
  
end

app/models/decode.rb
#To cache the decodes table data
require 'constant_cache'  

class Decode < ActiveRecord::Base

  establish_connection :ref_area
  
  default_scope :order => :sort_order
  
  #The key that will be used to retrieve constants is the constant_value
  caches_constants :key => :constant_value
  
  #association creator
  belongs_to :creator, :class_name => 'User', :foreign_key => "created_by"
  
  #association updator
  belongs_to :updator, :class_name => 'User', :foreign_key => "updated_by"
  
  ANY = "ANY"
  
  def self.all_values_by_decode_name(decode_name)
    Decode.find_all_by_name(decode_name).map(&:id)
  end
  
  #Used by formtastic for dropdowns
  def to_label
    display_value
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product

  def full_price
    unit_price * quantity
  end
end

app/models/omsitem.rb
class Omsitem < ActiveRecord::Base
  
  belongs_to :omsaccount
  belongs_to :pcsale
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :cart
  has_many :transactions, :class_name => "OrderTransaction"

  attr_accessor :card_number, :card_verification

  validate_on_create :validate_card

  def purchase
    response = process_purchase
    transactions.create!(:action => "purchase", :amount => price_in_cents, :response => response)
    cart.update_attribute(:purchased_at, Time.now) if response.success?
    response.success?
  end

  def price_in_cents
    (cart.total_price*100).round
  end

  def express_token=(token)
    self[:express_token] = token
    if new_record? && !token.blank?
      details = EXPRESS_GATEWAY.details_for(token)
      self.express_payer_id = details.payer_id
      self.first_name = details.params["first_name"]
      self.last_name = details.params["last_name"]
    end
  end

  private

  def process_purchase
    if express_token.blank?
      STANDARD_GATEWAY.purchase(price_in_cents, credit_card, standard_purchase_options)
    else
      EXPRESS_GATEWAY.purchase(price_in_cents, express_purchase_options)
    end
  end

  def standard_purchase_options
    {
      :ip => ip_address,
      :billing_address => {
        :name     => "Ritvvij Parrikh ",
        :address1 => "123 Main St.",
        :city     => "New York",
        :state    => "NY",
        :country  => "US",
        :zip      => "10001"
      }
    }
  end

  def express_purchase_options
    {
      :ip => ip_address,
      :token => express_token,
      :payer_id => express_payer_id
    }
  end

  def validate_card
    if express_token.blank? && !credit_card.valid?
      credit_card.errors.full_messages.each do |message|
        errors.add_to_base message
      end
    end
  end

  def credit_card
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(
      :type               => card_type,
      :number             => card_number,
      :verification_value => card_verification,
      :month              => card_expires_on.month,
      :year               => card_expires_on.year,
      :first_name         => first_name,
      :last_name          => last_name
    )
  end
end

app/models/pcaddon.rb
class Pcaddon < ActiveRecord::Base
  
  belongs_to :pcfeature
  
end

app/models/pcbooster.rb
class Pcbooster < ActiveRecord::Base
  
  belongs_to :pcfeature
  
end

app/models/pccoupon.rb
class Pccoupon < ActiveRecord::Base
  
  belongs_to :pcproduct_sale, :class_name => 'PcSale', :foreign_key => "pcproduct_saleid"
  
end

app/models/pcplan.rb
class Pcplan < ActiveRecord::Base
  
  belongs_to :pcproduct_sale, :class_name => 'PcSale', :foreign_key => "pcproduct_saleid"
  
end

app/models/pcsale.rb
class Pcsale < ActiveRecord::Base
  
  belongs_to :pcsaleable, :polymorphic => true
  
end

app/models/pcusage.rb
class Pcusage < ActiveRecord::Base
  
  belongs_to :pcfeature
  belongs_to :country
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
end

app/models/region.rb
class Region < ActiveRecord::Base
  
  establish_connection :ref_area
  
  default_scope :order => :name
  belongs_to :country
  has_many :cities
  
end

app/models/ucontact.rb
class Ucontact < ActiveRecord::Base
  
  establish_connection "op_#{RAILS_ENV}"
  
  OP_PHONE_TYPES = Decode.find_all_by_name("OP_Phone_Type")
  belongs_to :user
  belongs_to :country
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_one :usr
  has_one :ucontact  
  accepts_nested_attributes_for :usr, :ucontact
  has_one :user_local
  
  validates_presence_of :login_email
  validates_presence_of :username
  validates_associated :usr, :ucontact
  validates_wholesomeness_of :username, :if => lambda{|user| user.username.present? }

  def validate
   # validate_login_email
  end
  
  def validate_login_email
    unless EmailVeracity::Address.new(login_email).valid?
      errors.add(:login_email, "is invalid")
    end
  end
  
  acts_as_authentic do |a|
    a.logged_in_timeout = 100.minutes # default is 10.minutes
    a.validates_format_of_login_field_options :with => /^\w+$/, :message => "only numbers, letters and underscore allowed"
  end
  
  def self.find_by_username_or_login_email(login)
    find_by_username(login) || find_by_login_email(login)
  end
  
  def to_param
    username
  end
  
  def to_s
    [usr.first_name, usr.last_name].join(' ')
  end
  
  def self.curr_user
    Thread.current[:curr_user]
  end
  
  def self.curr_user=(user)
    #Setting the user to nil on logout
    #    raise(ArgumentError,
    #      "Invalid user. Expected an object of class 'User', got #{user.inspect}") unless user.is_a?(User)
    Thread.current[:curr_user] = user
  end
  
  def self.cid
    curr_user.id
  end
  
end

app/models/usr.rb
class Usr < ActiveRecord::Base
  establish_connection "op_#{RAILS_ENV}"
  belongs_to :user
  
  validates_presence_of :first_name, :last_name
  
end

app/views/layouts/_header.html.haml
#flash_messages
  - flash.each do |name, msg|
    = content_tag :div, msg, :class => "flash #{name}" if msg.is_a?(String)
        
- if @user && !@user.new_record?
  %h1
    = @user.username || @user.login_email
  
%br

app/views/layouts/_logo_box.html.haml
= image_tag('logo.png')
.home{:class => (request.request_uri == root_path || (current_user && request.request_uri == polymorphic_path(current_user))) ? "current" : nil}
    = link_to "Homepage", root_path

app/views/layouts/_old_browser.html.erb
<!--[if lt IE 7]>
    <div style='border: 1px solid #F7941D; background: #FEEFDA; text-align: center; clear: both; height: 75px; position: relative;'>
    <div style='position: absolute; right: 3px; top: 3px; font-family: courier new; font-weight: bold;'><a href='#' onclick='javascript:this.parentNode.parentNode.style.display="none"; return false;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-cornerx.jpg' style='border: none;' alt='Close this notice'/></a></div>
    <div style='width: 640px; margin: 0 auto; text-align: left; padding: 0; overflow: hidden; color: black;'>
    <div style='width: 75px; float: left;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-warning.jpg' alt='Warning!'/></div>
    <div style='width: 275px; float: left; font-family: Arial, sans-serif;'>
    <div style='font-size: 14px; font-weight: bold; margin-top: 12px;'>You are using an outdated browser</div>
    <div style='font-size: 12px; margin-top: 6px; line-height: 12px;'>For a better experience using this site, please upgrade to a modern web browser.</div>
    </div>
    <div style='width: 75px; float: left;'><a href='http://www.firefox.com' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-firefox.jpg' style='border: none;' alt='Get Firefox 3.5'/></a></div>
    <div style='width: 75px; float: left;'><a href='http://www.browserforthebetter.com/download.html' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-ie8.jpg' style='border: none;' alt='Get Internet Explorer 8'/></a></div>
    <div style='width: 73px; float: left;'><a href='http://www.apple.com/safari/download/' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-safari.jpg' style='border: none;' alt='Get Safari 4'/></a></div>
    <div style='float: left;'><a href='http://www.google.com/chrome' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-chrome.jpg' style='border: none;' alt='Get Google Chrome'/></a></div>
    </div>
    </div>
<![endif]-->

app/views/layouts/_top_bar.html.haml
= link_to " Open Profiles ", :popup => :true
= link_to " Organize Mosaic ", :popup => :true
= link_to " Work Backstage ", nil, :class => :orange
- if logged_in?
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
  = link_to " My Account ", :popup => :true
  = link_to " My Profile ", edit_registration_path, :popup => :true
  = link_to "Logout #{current_user}", destroy_user_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Va</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html{ "xml:lang" => "en", :lang => "en", :xmlns => "http://www.w3.org/1999/xhtml" }
  %head
    %meta{ :content => "text/html;charset=UTF-8", "http-equiv" => "content-type" }
    = javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery?
    = stylesheet_link_tag 'reset', 'ui-lightness/jquery-ui-1.7.2.custom', 'jquery.autocomplete', 'application', 'colorbox', :cache => 'base'
    = javascript_include_tag 'jquery-1.4.2.min', 'jquery-ui-1.7.2.custom.min', 'jquery.colorbox-min', 'jquery.autocomplete.pack', 'jquery.validate.pack', 'application', :cache => 'base'
    
  %body
    #container
      #header
        = #render :partial => "layouts/top_bar"
      	  
      #sidebar.left
        = render :partial => "layouts/logo_box"
        = yield(:sidebar)
        
      #content.right
        = render :partial => "layouts/header"
        = yield
        
      .clear
      = render :partial => "layouts/old_browser"